# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6439559d6a216b47d0f4b43600fb77e4125c45d1038d6d4c9df48c78deb66b972d98da8b2a70e1d33655f145c5ddbefdf81db3faebaaf3d2cb7d51377283d083

test:
  secret_key_base: 937b9f4b7f656b13a6ef7d65b57924066aafe2019868666ad49b44f588571baed28d360b26cc94b82e10a6727cf620f24c54b40e64be4ae19e7abca41dabb145

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
